# Configurazione del modulo NER-Giuridico per MERL-T

# Configurazione generale
general:
  language: "it"
  debug: false
  log_level: "INFO"
  cache_dir: "/Users/guglielmo/Desktop/CODE/MERL-T/src/data/ner/cache"

# Configurazione dei modelli
models:
  # Modello principale per NER basato su transformer
  transformer:
    model_name: "dbmdz/bert-base-italian-xxl-cased"
    max_length: 512
    batch_size: 16
    device: "cpu" # oppure "cpu"
    quantization: true # impostare a true per ottimizzare le prestazioni su hardware limitato
  
  # Modello SpaCy per supporto linguistico
  spacy:
    model_name: "it_core_news_lg"
    disable: ["parser", "ner"] # disabilitiamo il NER nativo di spaCy
  
  # Modello rule-based per pattern matching
  rule_based:
    enable: false
    patterns_dir: "../data/patterns"
    use_regex: true
    use_gazetteer: true

# Configurazione delle entità
entities:
  # Riferimenti normativi
  riferimenti_normativi:
    enabled: true
    subtypes:
      - codici
      - leggi
      - decreti_legge
      - decreti_legislativi
      - regolamenti_ue
      - direttive_ue
      - trattati
      - convenzioni
      - accordi
    patterns_file: "patterns_normativi.json"
    
  # Riferimenti giurisprudenziali
  riferimenti_giurisprudenziali:
    enabled: true
    subtypes:
      - sentenze
      - ordinanze
      - provvedimenti
      - decreti
    patterns_file: "patterns_giurisprudenziali.json"
    
  # Concetti giuridici
  concetti_giuridici:
    enabled: true
    gazetteer_file: "concetti_giuridici.json"

# Configurazione della pipeline di preprocessing
preprocessing:
  tokenization:
    use_spacy: true
    custom_tokenizer: false
  normalization:
    lowercase: false
    remove_accents: false
    normalize_spaces: true
  segmentation:
    use_spacy: true
    max_segment_length: 512
    overlap: 128

# Configurazione della normalizzazione delle entità
normalization:
  enable: true
  canonical_forms_file: "../data/canonical_forms.json"
  abbreviations_file: "../data/abbreviations.json"
  use_knowledge_graph: false
  knowledge_graph:
    url: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"

# Configurazione dell'API
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  rate_limit: 100 # richieste al minuto
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST"]
  endpoints:
    health: "/health"
    recognize: "/api/v1/recognize"
    batch: "/api/v1/batch"
    feedback: "/api/v1/feedback"

# Configurazione dell'integrazione con MoE
moe_integration:
  enable: false
  router_url: "http://localhost:8001/api/v1/route"
  authentication:
    type: "api_key"
    key_name: "X-API-Key"
    key_value: "${MOE_API_KEY}"

# Configurazione del monitoraggio
monitoring:
  enable: true
  prometheus:
    enable: true
    port: 9090
  logging:
    file: "/var/log/ner_giuridico.log"
    rotation: "1 day"
    retention: "30 days"
  tracing:
    enable: false
    jaeger_endpoint: "http://localhost:14268/api/traces"

# Configurazione dell'interfaccia di annotazione
annotation:
  tool: "label-studio" # oppure "doccano", "prodigy", "custom"
  host: "0.0.0.0"
  port: 8080
  data_dir: "../data/annotation"
  export_format: "spacy"
  project_name: "MERLT-NER"
